name = "PyCallCoolProp"
uuid = "e6e7dab9-4f3c-4707-a4e2-5f5a08172be1"
authors = ["marcus ashford"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
PyCall = "1.92"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
